apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -preproduction
resources: [../linode-common]
images:
  - name: registry.invalid/infinite-ocean/spyglass-engine
    newName: ghcr.io/tinfoyle/spyglass-engine
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
  - name: registry.invalid/infinite-ocean/infinite-ocean-website
    newName: ghcr.io/tinfoyle/infinite-ocean-website
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
patches:
  - path: environment-patch.yaml
