<script setup lang="ts">
import { usePublicSeo } from "~/composables/usePublicSeo";
usePublicSeo({ title: "Affiliate program terms · Infinite Ocean", path: "/affiliate-terms", description: "Current launch status and governing boundaries for the Infinite Ocean Affiliate program." });
</script>

<template>
  <article class="legal-copy section-frame">
    <p class="eyebrow">Launch policy · version 1 candidate</p><h1>Affiliate program terms</h1>
    <p class="lede"><strong>Enrollment is not currently open.</strong> The commercial policy below is owner-approved and implemented, but remains a legal and release draft until Infinite Ocean publishes the final terms and opens the program. It is not yet an operative earnings promise.</p>
    <h2>How enrollment works</h2><p>An Affiliate uses their ordinary Infinite Ocean login and receives a generated public code only after accepting the then-current published terms with recent strong authentication. A referred customer must actively enter or apply the code during checkout review.</p>
    <h2>Required disclosure</h2><p>Affiliates must clearly and conspicuously disclose near any endorsement or referral code that they may receive recurring value from qualifying purchases. Claims about Spyglass must be truthful and must not promise unavailable capabilities, prices or outcomes.</p>
    <h2>Qualifying subscription earnings</h2><p>The eligible launch offer is the $50.00 USD monthly team subscription before tax. Its initial fully paid invoice and every qualifying paid renewal create a $10.00 earning at full price. A customer discount applies the same percentage to the earning, so a 10% subscription discount creates a $9.00 earning. Positive eligible prorations earn at the same 20% rate. There is no maximum cycle count while the attributed subscription remains eligible.</p>
    <p>Optional commissioning, AI Token top-ups and promotional Token grants never earn commission. Stripe-calculated tax does not increase or reduce the earning. Failed, partial, void, zero-value and ineligible invoices earn nothing, and exact provider replays cannot duplicate an entry.</p>
    <h2>Rolling availability</h2><p>Each earning begins pending. The next qualifying fully paid invoice makes only the immediately preceding earning available and creates the next pending earning. If the subscription actually terminates before another qualifying invoice, the final pending earning expires; scheduling a cancellation does not void it. Available earnings are not clawed back merely because a subscription later ends.</p>
    <h2>Refunds and adverse payments</h2><p>Any successful non-zero Refund, finalized non-zero credit note or final lost dispute affecting the eligible subscription charge voids the complete earning for that invoice through immutable reversal evidence. Pending, draft, voided or won adverse objects do nothing. An adverse event confined to commissioning or another ineligible line does not reverse the subscription earning.</p>
    <h2>Settlement</h2><p>Available earnings accrue first as billing credit for one Infinite Ocean Account owned by the Affiliate. Oldest available credit automatically reduces that Account's next Infinite Ocean invoice after Stripe calculates tax. Pending, voided, reversed or Support-reserved value cannot be spent, and unused available credit carries forward without an arbitrary product expiration.</p>
    <p>At $100.00 USD of available credit, the Affiliate becomes eligible to ask Support for check-payment review. Checks are never automatic or directly self-service. The Affiliate must contact Support, complete recent passkey confirmation and provide the required identity, mailing-address and tax information. Support decides each check amount case by case; Spyglass only reserves and records value so it cannot be settled twice.</p>
    <h2>Eligibility and lifecycle</h2><p>Launch enrollment is limited to U.S. persons and entities with a valid U.S. mailing address and approved payer tax documentation. This does not limit where referred customers may subscribe. Suspension stops new code use and attribution but preserves earnings from already attributed subscriptions. Permanent closure stops future attribution and earnings without canceling customer subscriptions or forfeiting already available credit.</p>
    <h2>Attribution, privacy and retention</h2><p>Self-referral is denied against Accounts owned by the Affiliate, and one subscription can lock at most one attribution. Referred customer identity and business content never appear in the Affiliate statement. Optional analytics consent does not create, alter or erase commercial attribution.</p>
    <p>Affiliate financial and audit records are retained for seven years after the later of closure or final relevant activity, then deleted or irreversibly minimized unless a scoped legal hold applies. Verified erasure disables the code, stops future earnings and removes unneeded data while preserving customer subscriptions, available credit and access-restricted evidence required during that retention period.</p>
    <h2>Support and changes</h2><p>Enrollment, code and rule versions remain recorded. Program changes apply according to the version locked to the attribution and applicable law. Questions may be sent to <a href="mailto:support@infiniteocean.net">support@infiniteocean.net</a>.</p>
  </article>
</template>
