export interface PublicFeature {
  slug: string;
  name: string;
  title: string;
  summary: string;
  purpose: string;
  workflows: ReadonlyArray<string>;
  boundaries: ReadonlyArray<string>;
  packageCode?: "knowledge" | "work" | "agents" | "finance" | "marketing" | "integrations";
}

export const publicFeatures: ReadonlyArray<PublicFeature> = [
  { slug: "your-turn", name: "Your Turn", title: "Decide with context", summary: "Questions, reviews, approvals and recovery in one action-first queue.", purpose: "Your Turn separates moments that need human judgment from routine operational work, then explains the exact decision and its Account context.", workflows: ["Answer an information request with an exact Knowledge fact", "Accept or return assigned Work for changes", "Inspect and decide a consequential Agent proposal", "Resolve uncertain external outcomes with independent confirmation"], boundaries: ["Approval payloads, policy versions and evidence digests remain visible", "Stale decisions are rejected and reloaded", "Dual-control recovery cannot be confirmed by its requester"] },
  { slug: "work", name: "Work", title: "Turn gaps into progress", summary: "Durable work, ownership, priorities and history across people and Agents.", purpose: "Work turns discovered gaps and planned outcomes into accountable items with explicit state, assignment and provenance.", workflows: ["Create and prioritize bounded work", "Assign people or governed Agent workflows", "Review outcomes and request changes", "Trace work back to source context"], boundaries: ["Account role and package mode govern every mutation", "Version conflicts require a fresh review", "Consequential results return through Your Turn"], packageCode: "work" },
  { slug: "knowledge", name: "Knowledge", title: "Build memory with evidence", summary: "Facts, documents, revisions and citations stay attributable.", purpose: "Knowledge gives the business a versioned memory without turning drafts or guesses into silent authority.", workflows: ["Capture scoped facts and cited claims", "Revise documents without losing history", "Publish reviewed revisions", "Use exact fact versions when resolving Work"], boundaries: ["Draft and published states remain distinct", "Sensitivity and scope travel with knowledge", "Answers cite exact fact versions"], packageCode: "knowledge" },
  { slug: "baseline", name: "Baseline", title: "See what is missing", summary: "A guided assessment connects evidence gaps to practical work.", purpose: "Baseline inventories the current operating picture, identifies evidence-backed gaps and proposes a reviewable plan.", workflows: ["Collect a bounded source inventory", "Review requirements and evidence", "Classify gaps and exceptions", "Approve proposed Work"], boundaries: ["Source grants are explicit and revocable", "Evidence decisions remain attributable", "Plan approval stays human-authorized"] },
  { slug: "agents", name: "Agents", title: "Delegate inside boundaries", summary: "Versioned personas, approved tools and inspectable runs.", purpose: "Agents help move routine work while keeping their instructions, tools, evidence and consequential proposals inspectable.", workflows: ["Publish versioned Personas", "Organize Boardrooms and conversations", "Run bounded work with approved tools", "Inspect events, artifacts and recovery state"], boundaries: ["A run cannot silently expand its capabilities", "Consequential operations require Your Turn approval", "Uncertain external effects enter recovery instead of being guessed"], packageCode: "agents" },
  { slug: "schedules", name: "Schedules", title: "Make recurrence explicit", summary: "Versioned schedules create governed work at reviewed times.", purpose: "Schedules make recurring operating rhythms visible, reviewable and suspendable.", workflows: ["Create and revise a schedule", "Inspect the next planned run", "Pause or resume recurrence", "Trace scheduled outcomes into Work and Agent runs"], boundaries: ["Schedules use Account authority and current versions", "Pausing does not erase history", "Execution remains subject to package and capability policy"] },
  { slug: "finance", name: "Finance", title: "Keep records governed", summary: "Balanced entries, reconciliation and approvals without mixing product billing.", purpose: "Finance supports accountable operational records while keeping Spyglass subscription billing in its own commercial boundary.", workflows: ["Maintain ledgers and posting accounts", "Draft balanced journal entries", "Reconcile statements and periods", "Route material decisions for approval"], boundaries: ["Entries must balance in one supported currency", "Evidence and reversal history remain immutable", "Product subscriptions are not customer finance records"], packageCode: "finance" },
  { slug: "marketing", name: "Marketing", title: "Move from plan to release", summary: "Governed campaigns, assets, channels and consequential publishing.", purpose: "Marketing connects planning and reviewed assets to bounded release operations.", workflows: ["Plan campaigns and revise assets", "Prepare channel releases", "Submit releases for review", "Activate, pause and complete campaigns"], boundaries: ["Publishing remains a consequential capability", "Asset and release revisions are versioned", "External uncertainty uses recovery rather than duplicate release"], packageCode: "marketing" },
  { slug: "integrations", name: "Integrations", title: "Connect without surrendering control", summary: "Scoped credentials, health evidence and bounded execution.", purpose: "Integrations connect external systems through explicit capabilities and revocable credential bindings.", workflows: ["Create and authorize a connection", "Bind, rotate or revoke credentials", "Inspect health and execution evidence", "Resolve uncertain external actions"], boundaries: ["Credentials are never exposed back to the browser", "Capabilities are connector-specific and scoped", "Revocation and recovery preserve an audit trail"], packageCode: "integrations" },
  { slug: "account-administration", name: "Account administration", title: "Keep authority understandable", summary: "Membership, roles, Account selection and package-aware access.", purpose: "Account administration makes ownership, billing authority, membership and effective package access explicit.", workflows: ["Select among authorized Accounts", "Invite and manage members", "Assign bounded roles", "Inspect current entitlements and billing state"], boundaries: ["The server remains the authorization authority", "Owner and billing authority are distinct", "Disabled packages explain access without leaking data"] },
  { slug: "security", name: "Security and recovery", title: "Protect consequential authority", summary: "Passkeys, strong reauthentication, session control and dual-control recovery.", purpose: "Security raises assurance in proportion to the operation instead of treating one login as permanent authority.", workflows: ["Enroll passkeys and recovery material", "Confirm privileged actions", "Review and revoke sessions", "Recover uncertain or lost access safely"], boundaries: ["Owner authority requires security enrollment", "Privileged operations require recent strong authentication", "Recovery and consequential confirmation preserve separation of duties"] },
  { slug: "export-lifecycle", name: "Export and lifecycle", title: "Leave with a traceable boundary", summary: "Account export, closure review, retention and privacy rights.", purpose: "Lifecycle controls make access, export, closure and erasure understandable rather than hiding them behind support requests.", workflows: ["Request and retrieve Account exports", "Review closure blockers and timing", "Cancel or complete closure", "Exercise privacy access and erasure choices"], boundaries: ["Legal, security and operational retention classes stay explicit", "Closure waits for governed blockers and timing", "Affiliate identity rights remain distinct from referred Account data"] }
];

export const featureBySlug = (slug: string): PublicFeature | undefined => publicFeatures.find((feature) => feature.slug === slug);
