import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "../_components/site-shell";

export const metadata: Metadata = { title: "Create your Account", description: "Create a free Infinite Ocean identity and Spyglass Account." };

export default function SignupPage() {
  return <main><SiteHeader /><section className="signup-layout shell"><div className="signup-copy"><p className="eyebrow"><span /> Start with Spyglass</p><h1>Your first clear view is free.</h1><p>Create one Infinite Ocean identity and a Spyglass Account for your business. You can invite a team, join other Accounts, and add paid packages later.</p><ul><li>No payment information required</li><li>One identity can belong to multiple Accounts</li><li>Package access is explicit and changeable</li><li>Your business data remains isolated</li></ul><p>Already have an identity? <Link href="https://app.infiniteocean.net">Log in to Spyglass</Link>.</p></div><div className="signup-card"><span>FREE ACCOUNT</span><h2>Create your Infinite Ocean identity</h2><form className="signup-form" action="https://app.infiniteocean.net/signup" method="post"><label>Your name<input name="name" autoComplete="name" required placeholder="Avery Johnson" /></label><label>Work email<input name="email" type="email" autoComplete="email" required placeholder="avery@company.com" /></label><label>Business name<input name="account_name" autoComplete="organization" required placeholder="Northstar Studio" /></label><button className="button primary" type="submit">Continue securely <span aria-hidden="true">→</span></button></form><p className="legal">By continuing, you agree to Infinite Ocean&apos;s <Link href="/terms">Terms</Link> and acknowledge the <Link href="/privacy">Privacy Notice</Link>.</p><p className="integration-note"><strong>Phase 2 integration boundary:</strong> identity verification and Account creation complete on the private Spyglass application origin. Payment information is not requested for the free plan.</p></div></section><SiteFooter /></main>;
}
