apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-accounts.yaml
  - account-api.yaml
  - app-router.yaml
  - app-api.yaml
  - admission-api.yaml
  - billing-worker.yaml
  - notification-worker.yaml
  - entitlement-worker.yaml
  - account-lifecycle-worker.yaml
  - work-reconciler.yaml
  - route-receipt-worker.yaml
  - policy.yaml
