apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-api
  namespace: spyglass-reference
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-router
  namespace: spyglass-reference
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-api
  namespace: spyglass-reference
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-worker
  namespace: spyglass-reference
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-worker
  namespace: spyglass-reference
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: entitlement-worker
  namespace: spyglass-reference
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: work-reconciler
  namespace: spyglass-reference
automountServiceAccountToken: false
