<template>
  <section aria-labelledby="help-title">
    <p class="eyebrow">Admin guide</p><h1 id="help-title">Using this console</h1>
    <div class="report-card"><h2>Traffic &amp; logs</h2><ol><li>Choose a period, up to the last seven days.</li><li>Enter a review reference and reason, then select Load traffic.</li><li>Use Summary for request totals, sites and response codes; Unique IPs to filter or download addresses; Request logs for the latest 200 requests.</li></ol><p>Requests include bots, page assets and checks. Shared networks can put several people behind one IP. Missing or incomplete logs are shown as warnings, not zero traffic.</p></div>
    <div class="report-card"><h2>Product analytics</h2><ol><li>Start with Event only and a minimum of five browsers.</li><li>Select Run report to see consented website and app events.</li><li>Group by page, offer or button when you need more detail.</li></ol><p>Groups smaller than the minimum are hidden. An empty report on Stage can be expected even while the traffic report shows requests. Reports do not contain customer content.</p></div>
    <div class="report-card"><h2>Staff access</h2><p>Sign in with your approved Google account, then enter the code for Spyglass Admin from your authenticator app. First-time staff scan a setup QR code and save recovery codes. A platform owner must assign your staff role.</p><p>Roles control the modules you can open. Traffic logs require an Operations administrator; product analytics requires Analytics or Operations administrator. Staff role changes happen through the documented operator command, outside this console.</p><p>Sensitive changes may ask for another authenticator code. Sign out when finished. Sessions expire after eight hours or thirty minutes of inactivity. Revoking staff access also invalidates the session.</p></div>
    <div class="report-card"><h2>Customer support and other modules</h2><p>Customer lookup uses an exact identifier and records your reference and reason. An account view is read-only and expires after fifteen minutes by default. Close it when the support task is finished.</p><p>Billing, privacy and affiliate tools are available only to the assigned roles. Read each action before submitting it. Future back-office tools belong in separate modules with their own permissions and audit records.</p></div>
  </section>
</template>
