apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../reference
  - platform.yaml
  - platform-policy.yaml
  - platform-jobs.yaml
  - cell-a.yaml
  - cell-b.yaml
patches:
  - path: remove-cell-reference.yaml
