apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../reference
  - platform.yaml
  - platform-policy.yaml
  - platform-jobs.yaml
  - cell-a.yaml
  - cell-b.yaml
patches:
  - path: remove-cell-reference.yaml
  - target: {group: apps, version: v1, kind: Deployment, name: admission-api}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: admission-api}
      spec:
        template:
          spec:
            containers:
              - name: admission-api
                env:
                  - name: SPYGLASS_ADMISSION_CELL_IDS
                    value: cell-us-east-01,cell-us-west-01
                  - name: SPYGLASS_WORKLOAD_CLIENT_IDENTITIES
                    value: spiffe://infiniteocean.net/spyglass/cells/cell-us-east-01/app-api,spiffe://infiniteocean.net/spyglass/cells/cell-us-west-01/app-api,spiffe://infiniteocean.net/spyglass/cells/cell-us-east-01/agent-dispatch-worker,spiffe://infiniteocean.net/spyglass/cells/cell-us-west-01/agent-dispatch-worker
  - target: {group: apps, version: v1, kind: Deployment, name: tool-router}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: tool-router}
      spec:
        template:
          spec:
            containers:
              - name: tool-router
                env:
                  - name: SPYGLASS_WORKLOAD_CLIENT_IDENTITIES
                    value: spiffe://infiniteocean.net/spyglass/cells/cell-us-east-01/runner-broker,spiffe://infiniteocean.net/spyglass/cells/cell-us-west-01/runner-broker
