#!/usr/bin/env bash
set -euo pipefail

overlay_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd "$overlay_dir/../../.." && pwd)"
reference_dir="$repository_root/deploy/kubernetes/reference"
sources=(
  app-api.yaml
  work-reconciler.yaml
  baseline-maintenance-worker.yaml
  route-receipt-worker.yaml
  agent-dispatch-worker.yaml
  schedule-execution-worker.yaml
  agent-projection-worker.yaml
  runner-controller.yaml
  runner-broker.yaml
)
check_only=false
if [[ ${1:-} == --check ]]; then
  check_only=true
elif [[ $# -ne 0 ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

generate_cell() {
  local suffix="$1"
  local cell_id="$2"
  local target="$overlay_dir/linode-common/cell-$suffix.yaml"
  local temporary
  temporary="$(mktemp)"
  trap 'rm -f -- "$temporary"' RETURN

  {
    printf '# Code generated by deploy/kubernetes/overlays/generate-linode-cells.sh; DO NOT EDIT.\n'
    local separator=''
    local source
    for source in "${sources[@]}"; do
      printf '%s' "$separator"
      sed \
        -e "s/cell-reference/cell-$suffix/g" \
        -e "s/spyglass.io\/cell: reference/spyglass.io\/cell: cell-$suffix/g" \
        -e "s/value: \"reference\"/value: \"$cell_id\"/g" \
        -e "s|/cells/reference/|/cells/$cell_id/|g" \
        "$reference_dir/$source"
      separator=$'---\n'
    done
  } >"$temporary"

  if [[ ! -f "$target" ]] || ! cmp -s "$temporary" "$target"; then
    if [[ "$check_only" == true ]]; then
      echo "$target is stale; run deploy/kubernetes/overlays/generate-linode-cells.sh" >&2
      exit 1
    fi
    mv -- "$temporary" "$target"
  fi
}

generate_cell a cell-us-east-01
generate_cell b cell-us-west-01
